apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: playground-local

resources:
  - "../../base"
  - "namespace.yaml"

commonLabels:
  env: local 

images:
  - name: kennethreitz/httpbin
    newTag: latest

replicas:
  - name: httpbin-deployment
    count: 1
